url: https://ben-sanati.github.io
baseurl: ""

# Site Settings
title: Ben Sanati
description: "Hey, I'm Ben"
keywords: "DL, DRL, MARL, ZSG, Continual Learning"
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: 
    output: true
markdown: 

highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
